version: '3.8'

services:
  frontend:
    build:
      context: ./calculator-app
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://localhost:8080

  backend:
    build:
      context: ./calculator-api
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
